###### General ######
spring.application.name=ToDo_APP
server.port=8080

###### Spring Boot Actuator ######
management.endpoints.web.exposure.include=*

###### Configuring JSP ######
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

###### Logging & Profile ######
logging.level.org.springframework=info
logging.level.org.example.todo_temp=debug
spring.mvc.format.date=yyyy-MM-dd
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.defer-datasource-initialization=true
#spring.profiles.active=default
#spring.profiles.active=dev